-- CREATE TABLE `LOCATION` (`ID` VARCHAR(25) NOT NULL,`Name` VARCHAR(80) NULL,PRIMARY KEY (`ID`));
INSERT INTO LOCATION VALUES ('l1', 'Abu-Dabi');
INSERT INTO LOCATION VALUES ('l2', 'Paris');
INSERT INTO LOCATION VALUES ('l3', 'Nairobi');
INSERT INTO LOCATION VALUES ('l4', 'Lagos');
INSERT INTO LOCATION VALUES ('l5', 'Asaba');
INSERT INTO LOCATION VALUES ('l6', 'Budapest');
--
-- SELECT * from "location"